import logo from "./logo.svg";
const Data = [
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Palace",
          city: "Mumbai",
          state: "MH",
          rooms: "3",
          price: 5000,
          floorspace: 1000,
          extras: ["elevators", "gym", "swimmingpool", "finishedbasement"],
          homeType: "Apartment",
          image: logo,
     },
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Nagar",
          city: "Pune",
          state: "MH",
          rooms: "4",
          price: 2000,
          floorspace: 2000,
          extras: ["elevators", "gym", "swimmingpool", "finishedbasement"],
          homeType: "Flat",
          image: logo,
     },
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Palace",
          city: "Nashik",
          state: "MH",
          rooms: "3",
          price: 2000,
          floorspace: 1500,
          extras: ["elevators", "gym", "finishedbasement"],
          homeType: "Apartment",
          image: logo,
     },
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Palace",
          city: "Solapur",
          state: "MH",
          rooms: "2",
          price: 3000,
          floorspace: 2500,
          extras: ["elevators", "gym", "swimmingpool"],
          homeType: "Room",
          image: logo,
     },
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Palace",
          city: "Nagpur",
          state: "MH",
          rooms: "1",
          price: 3000,
          floorspace: 3000,
          extras: ["elevators", "swimmingpool", "finishedbasement"],
          homeType: "Apartment",
          image: logo,
     },
     {
          postedBy: "Pawankumar",
          postedOn: "05/04/2020",
          address: "A-204,Raj Palace",
          city: "Kolhapur",
          state: "MH",
          rooms: "3",
          price: 4000,
          floorspace: 4000,
          extras: ["gym", "swimmingpool", "finishedbasement"],
          homeType: "Room",
          image: logo,
     },
];
export default Data;
